import type { COAOption, RunningEstimate } from "@/lib/mock-data";
import type { GCCId } from "@/lib/gcc-config";

// ── Posture-Driven Language ─────────────────────────────────────────────────

const POSTURE_VERBS: Record<string, string[]> = {
  ESCALATORY: ["Neutralize", "Degrade", "Disrupt", "Deny", "Dominate"],
  DEFENSIVE: ["Protect", "Defend", "Shield", "Preserve", "Secure"],
  BALANCED: ["Counter", "Respond to", "Synchronize", "Coordinate", "Engage"],
};

function selectPostureVerb(posture: string, index: number): string {
  const verbs = POSTURE_VERBS[posture] ?? POSTURE_VERBS.BALANCED;
  return verbs[index % verbs.length];
}

// ── Helpers ─────────────────────────────────────────────────────────────────

function truncate(text: string, maxLen: number): string {
  if (text.length <= maxLen) return text;
  return text.slice(0, maxLen) + "...";
}

function assessmentCycleHours(posture: string): number {
  return posture === "ESCALATORY" ? 12 : 24;
}

function citationsBlock(coa: COAOption): string {
  return [
    "REFERENCES / DOCTRINAL BASIS:",
    "  [1] JP 3-13, Information Operations, 27 Nov 2012 (C1, 20 Nov 2014)",
    "  [2] MCDP 3-32, Marine Air-Ground Task Force Information Operations, 2020",
    "  [3] FM 3-13, Information Operations, Oct 2023",
    "  [4] MCWP 3-32.1, Tactics, Techniques, and Procedures for MAGTF IO, 2019",
    "  [5] USCYBERCOM Legal Review Framework (Title 10/50 DCO authorities)",
    "  [6] USSOCOM PSYOP Approval Authority directive (current)",
    "",
    "TOOL PROVENANCE:",
    "  Generated by: IE-SYNC IO Planning Tool v2.1 (UNCLASSIFIED)",
    "  Generation method: COA-driven template assembly from Running Estimate + selected COA",
    "  AI assistance: None — rule-based template with human-supplied data",
    `  COA: ${coa.id} — ${coa.name} (v${coa.version}, ${coa.status})`,
    "  HUMAN REVIEW REQUIRED before operational use or commander briefing.",
  ].join("\n");
}

// ── Group tasks by capability for ANNEX I ───────────────────────────────────

function groupTasksByCapability(coa: COAOption): Map<string, typeof coa.tasks> {
  const groups = new Map<string, typeof coa.tasks>();
  for (const task of coa.tasks) {
    const existing = groups.get(task.capability) ?? [];
    existing.push(task);
    groups.set(task.capability, existing);
  }
  return groups;
}

// ── ANNEX I Generator ───────────────────────────────────────────────────────

export function generateAnnexIContent(
  coa: COAOption,
  estimate: RunningEstimate,
  _gcc: GCCId,
): string {
  const lines: string[] = [];

  // Header
  lines.push(estimate.classification);
  lines.push("COPY ___ OF ___ COPIES");
  lines.push("III MEF // G7 // 1ST MARINE INFORMATION GROUP");
  lines.push(`DTG: ${estimate.dtg}`);
  lines.push(estimate.operationName);
  lines.push("");

  // Title
  lines.push("ANNEX I (INFORMATION) TO OPORD 001");
  lines.push("REFERENCES: See Basic Plan");
  lines.push(
    `SELECTED COA: ${coa.id} — ${coa.name} (Status: ${coa.status}, Posture: ${coa.posture})`,
  );
  lines.push("");

  // Section 1: SITUATION
  lines.push("1. SITUATION");
  lines.push(
    `   a. Enemy Information Capabilities: ${truncate(estimate.ieSituation, 400)}`,
  );
  lines.push(
    `   b. Friendly Information Capabilities: ${estimate.friendlyCapabilities.join("; ")}`,
  );
  lines.push(
    `   c. Information Environment Condition: ${estimate.ieCondition}. ${truncate(estimate.ieSituation, 300)}`,
  );
  lines.push("");

  // Section 2: MISSION
  lines.push("2. MISSION");
  lines.push(`   ${estimate.missionStatement}`);
  lines.push("");

  // Section 3: EXECUTION
  lines.push("3. EXECUTION");
  lines.push(`   a. CDRU Objective: ${estimate.cdruObjective}`);
  lines.push(`   b. IO Priority: ${estimate.priority}`);

  // Lines of Effort
  lines.push("   c. Lines of Effort:");
  for (const loe of coa.linesOfEffort) {
    lines.push(`      ${loe}`);
  }

  // Key Tasks grouped by capability
  lines.push(`   d. Key Tasks — IO Capabilities (COA: ${coa.id}):`);
  const grouped = groupTasksByCapability(coa);
  let verbIdx = 0;
  for (const [capability, tasks] of grouped) {
    lines.push(`      ${capability}:`);
    for (const task of tasks) {
      const verb = selectPostureVerb(coa.posture, verbIdx);
      lines.push(
        `        - [${task.id}] ${verb}: ${task.description} (Owner: ${task.owner}, NLT: ${task.nlt}, Phase: ${task.phase})`,
      );
      verbIdx++;
    }
  }

  // Information Effects
  lines.push("   e. Information Effects:");
  for (const effect of coa.informationEffects) {
    lines.push(
      `      - [${effect.id}] ${effect.effectType} — Target: ${effect.target}`,
    );
    lines.push(`        Description: ${effect.description}`);
    lines.push(`        MOE Linked: ${effect.moeLinked.join(", ")}`);
  }

  // Required Authorities
  lines.push("   f. Required Authorities:");
  for (const auth of coa.authorityRequirements) {
    const legalTag = auth.legalReview ? " [LEGAL REVIEW REQUIRED]" : "";
    lines.push(
      `      - ${auth.authority} (${auth.capability}): ${auth.status}${legalTag}`,
    );
  }

  // Coordinating Instructions
  lines.push("   g. Coordinating Instructions:");
  const cycleHours = assessmentCycleHours(coa.posture);
  let coordNum = 1;
  lines.push(
    `      (${coordNum}) IO Synchronization Meeting (IOSM): Daily 0600Z.`,
  );
  coordNum++;
  lines.push(
    `      (${coordNum}) MOE/MOP Assessment Cycle: Every ${cycleHours} hours.`,
  );
  coordNum++;
  lines.push(
    `      (${coordNum}) Human Review Required: All AI-assisted IO planning products require human analyst validation.`,
  );
  coordNum++;

  // Pending authorities
  for (const auth of coa.authorityRequirements) {
    if (auth.status === "PENDING") {
      lines.push(
        `      (${coordNum}) ${auth.authority}: Submit NLT ${auth.requiredBy} before execution.`,
      );
      coordNum++;
    }
  }

  // Legal review requirements
  for (const auth of coa.authorityRequirements) {
    if (auth.legalReview) {
      lines.push(
        `      (${coordNum}) Legal review required for ${auth.capability} actions (${auth.authority}).`,
      );
      coordNum++;
    }
  }
  lines.push("");

  // Section 4: ADMINISTRATION AND LOGISTICS
  lines.push("4. ADMINISTRATION AND LOGISTICS");
  lines.push(
    "   a. IO products will be coordinated through the MIG S-4 for production and dissemination.",
  );
  lines.push(
    "   b. MISO material production at current MISO Support Facility (MSF) rate.",
  );
  lines.push(
    "   c. Cyber operations resource allocation per CYBERCOM TASKORD.",
  );
  lines.push(
    "   d. EW asset allocation per INDOPACOM EMOE deconfliction directive.",
  );
  lines.push(`   e. Resource Requirement: ${coa.resourceRequirement}`);
  lines.push("");

  // Section 5: COMMAND AND SIGNAL
  lines.push("5. COMMAND AND SIGNAL");
  lines.push("   a. IO Cell: MIG COC, Bldg 1532, Camp Hansen.");
  lines.push(
    "   b. Primary: SIPRNET chat — III MEF G7/IO Channel. Alternate: TAC-1 (freq TBD).",
  );
  lines.push("   c. Reports: Per unit SOP and ITREP format.");
  lines.push("");

  // Signature block
  lines.push("ACKNOWLEDGE");
  lines.push("//SIGNED//");
  lines.push("[IO OFFICER SIGNATURE BLOCK]");
  lines.push("");
  lines.push(estimate.classification);
  lines.push("");

  // Citations
  lines.push(citationsBlock(coa));

  return lines.join("\n");
}

// ── ITCO Generator ──────────────────────────────────────────────────────────

export function generateITCOContent(
  coa: COAOption,
  estimate: RunningEstimate,
  _gcc: GCCId,
): string {
  const lines: string[] = [];

  // Header
  lines.push(estimate.classification);
  lines.push("INFORMATION TASKING AND COORDINATION ORDER (ITCO)");
  lines.push(`DTG: ${estimate.dtg}`);
  lines.push(`OPERATION: ${estimate.operationName}`);
  lines.push("FROM: CG III MEF G7 / 1ST MIG");
  lines.push("TO: ALL IO ELEMENTS");
  lines.push(`SELECTED COA: ${coa.id} — ${coa.name}`);
  lines.push("");
  lines.push("ITCO SERIAL: 001-25");
  lines.push("");

  // Section 1: SITUATION SUMMARY
  lines.push("1. SITUATION SUMMARY");
  lines.push(`   IE Condition: ${estimate.ieCondition}`);
  lines.push(
    `   Priority Threat: ${truncate(estimate.ieSituation, 200)}`,
  );
  lines.push(`   COA Posture: ${coa.posture}`);
  lines.push("");

  // Section 2: IO TASKS BY CAPABILITY
  lines.push(`2. IO TASKS BY CAPABILITY (COA: ${coa.id})`);
  coa.tasks.forEach((task, idx) => {
    const verb = selectPostureVerb(coa.posture, idx);
    lines.push("");
    lines.push(`   TASK ${idx + 1} — ${task.capability}`);
    lines.push(`   Unit: ${task.owner}`);
    lines.push(`   Task: ${verb} ${task.description}`);
    lines.push(`   NLT: ${task.nlt} from order receipt.`);
    lines.push(`   AUTHORITY: ${task.authority}`);
    lines.push(`   MOE Supported: ${task.moeSupported.join(", ")}`);
    lines.push(`   Phase: ${task.phase}`);
  });
  lines.push("");

  // Section 3: IO SYNCHRONIZATION
  lines.push("3. IO SYNCHRONIZATION");
  for (const step of coa.sequence) {
    lines.push(`   ${step}`);
  }
  const cycleHours = assessmentCycleHours(coa.posture);
  lines.push(`   MOE/MOP Collection: Every ${cycleHours} hours.`);
  lines.push(
    "   Human Analyst Validation: Required for all AI-assisted assessments.",
  );
  lines.push("");

  // Section 4: REPORTING
  lines.push("4. REPORTING");
  lines.push("   Standard ITREP requirements.");
  lines.push("");

  // Section 5: SPECIAL INSTRUCTIONS
  lines.push("5. SPECIAL INSTRUCTIONS");
  coa.authorityRequirements.forEach((auth, idx) => {
    const legalNote = auth.legalReview
      ? " Legal review required prior to execution."
      : "";
    lines.push(
      `   (${idx + 1}) ${auth.capability} — ${auth.authority}: Status ${auth.status}. Required by ${auth.requiredBy}.${legalNote}`,
    );
  });
  lines.push("");

  // Signature block
  lines.push("ACKNOWLEDGE");
  lines.push("//SIGNED//");
  lines.push("CG III MEF G7 / IO");
  lines.push("");
  lines.push(estimate.classification);
  lines.push("");

  // Citations
  lines.push(citationsBlock(coa));

  return lines.join("\n");
}
