"use client";

import { useState } from "react";
import { useIEStore } from "@/store/ie-store";
import { formatDTG } from "@/lib/utils";
import { GlossaryPanel } from "@/components/ui/GlossaryPanel";
import type { COAOption, AnnexGeneration, IOCapability } from "@/lib/mock-data";

type DocType = "annex-i" | "itco";

// ── Color maps ────────────────────────────────────────────────────────────
const COA_STATUS_COLOR: Record<string, string> = {
  APPROVED: "#10b981",
  COMMANDER_ENDORSED: "#0891b2",
  ANALYST_SELECTABLE: "#f59e0b",
  DRAFT: "#475569",
};

const POSTURE_COLOR: Record<string, string> = {
  ESCALATORY: "#ef4444",
  DEFENSIVE: "#10b981",
  BALANCED: "#f59e0b",
};

const RISK_COLOR: Record<string, string> = {
  CRITICAL: "#ef4444",
  HIGH: "#ef4444",
  MEDIUM: "#f59e0b",
  LOW: "#10b981",
  INFO: "#475569",
};

const AUTH_STATUS_COLOR: Record<string, string> = {
  OBTAINED: "#10b981",
  PENDING: "#f59e0b",
  NOT_REQUESTED: "#475569",
};

// ── Main Component ────────────────────────────────────────────────────────
export function AnnexGenerator() {
  const {
    runningEstimate,
    coaOptions,
    selectedCOA,
    setSelectedCOA,
    activeGCC,
    annexGenerating,
    annexGenProgress,
    lastGeneratedAnnex,
    setAnnexGenerating,
    setLastGeneratedAnnex,
    clearAnnexState,
  } = useIEStore();

  const [activeDoc, setActiveDoc] = useState<DocType>("annex-i");
  const [previewImpact, setPreviewImpact] = useState(false);
  const [copied, setCopied] = useState(false);
  const [genError, setGenError] = useState<string | null>(null);

  const activeCOA = coaOptions.find((c) => c.id === selectedCOA) ?? null;

  // ── Generate via API ──────────────────────────────────────────────────
  const handleGenerate = async () => {
    if (!selectedCOA) return;
    setGenError(null);
    setAnnexGenerating(true, 10);

    try {
      setAnnexGenerating(true, 30);

      const res = await fetch("/api/annex", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          docType: activeDoc,
          coaId: selectedCOA,
          gcc: activeGCC,
          overrideWarnings: true,
        }),
      });

      setAnnexGenerating(true, 70);

      const data = await res.json();

      if (!data.success) {
        setGenError(data.error ?? "Generation failed");
        setAnnexGenerating(false);
        return;
      }

      setLastGeneratedAnnex(data.annex);
    } catch (err) {
      setGenError(err instanceof Error ? err.message : "Network error");
      setAnnexGenerating(false);
    }
  };

  // ── Exports ───────────────────────────────────────────────────────────
  const handleExportTXT = () => {
    if (!lastGeneratedAnnex || !activeCOA) return;
    const m = lastGeneratedAnnex.metadata;
    const header = [
      "========================================",
      "COA LINKAGE METADATA",
      "========================================",
      `COA ID: ${m.selectedCoaId}`,
      `COA Name: ${activeCOA.name}`,
      `COA Version: ${m.selectedCoaVersion}`,
      `COA Status: ${m.selectedCoaStatus}`,
      `Generation Timestamp: ${m.generationTimestamp}`,
      `Generated By: ${m.generatedBy}`,
      `Planning Tool: ${m.planningToolId}`,
      `Document Hash: ${m.outputHash}`,
      `Human Review Status: ${m.humanReviewStatus}`,
      "========================================",
      "",
    ].join("\n");
    const full = header + lastGeneratedAnnex.content;
    const blob = new Blob([full], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${activeDoc.toUpperCase()}_${m.selectedCoaId}_${m.generationTimestamp.replace(/[:.]/g, "")}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleExportJSON = () => {
    if (!lastGeneratedAnnex || !activeCOA) return;
    const m = lastGeneratedAnnex.metadata;
    const jsonData = {
      exportedAt: new Date().toISOString(),
      docType: activeDoc,
      annex: { ...m },
      coa: {
        id: activeCOA.id,
        name: activeCOA.name,
        version: activeCOA.version,
        status: activeCOA.status,
        posture: activeCOA.posture,
      },
      content: lastGeneratedAnnex.content,
      generationTool: "IE-SYNC v2.1",
      humanReviewRequired: true,
    };
    const blob = new Blob([JSON.stringify(jsonData, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${activeDoc.toUpperCase()}_${m.selectedCoaId}_${m.generationTimestamp.replace(/[:.]/g, "")}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleCopy = () => {
    if (!lastGeneratedAnnex) return;
    navigator.clipboard.writeText(lastGeneratedAnnex.content).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    });
  };

  // ── Render ────────────────────────────────────────────────────────────
  return (
    <div className="p-4 h-full overflow-y-auto space-y-4">
      {/* ── Module Header ──────────────────────────────────────────────── */}
      <div className="flex items-center justify-between">
        <div>
          <div className="text-[#00d4ff] text-sm font-black tracking-widest">ANNEX I / ITCO GENERATOR</div>
          <div className="text-[#475569] text-xs font-mono">
            IO Planning Assistant — COA-Driven Document Generation
          </div>
        </div>
        <div className="flex items-center gap-3">
          {lastGeneratedAnnex && (
            <div className="flex items-center gap-1.5 text-xs text-[#f59e0b] border border-[#f59e0b] px-3 py-1 rounded">
              <span>!</span> HUMAN REVIEW REQUIRED
            </div>
          )}
          <div className="relative group">
            <button
              onClick={handleGenerate}
              disabled={!selectedCOA || annexGenerating}
              className="px-4 py-2 text-xs bg-[#1e3a5f] border border-[#00d4ff] text-[#00d4ff] rounded hover:bg-[#00d4ff15] disabled:opacity-50 disabled:cursor-not-allowed font-bold tracking-wider"
            >
              {annexGenerating ? "GENERATING..." : "GENERATE DOCUMENT"}
            </button>
            {!selectedCOA && !annexGenerating && (
              <div className="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 px-3 py-1.5 text-[10px] bg-[#1e3a5f] border border-[#ef4444] text-[#ef4444] rounded whitespace-nowrap opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none">
                Select a COA before generating
              </div>
            )}
          </div>
        </div>
      </div>

      {/* ── COA Selection Panel ────────────────────────────────────────── */}
      <div className="p-4 border border-[#1e3a5f] bg-[#070d1a] rounded space-y-3">
        <div className="text-[#00d4ff] text-[10px] font-bold tracking-widest">SELECT COURSE OF ACTION</div>
        <div className="grid grid-cols-1 gap-2">
          {coaOptions.map((coa) => (
            <button
              key={coa.id}
              onClick={() => {
                setSelectedCOA(selectedCOA === coa.id ? null : coa.id);
                clearAnnexState();
              }}
              className={`w-full text-left p-3 border rounded transition-colors ${
                selectedCOA === coa.id
                  ? "border-[#00d4ff] bg-[#00d4ff08]"
                  : "border-[#1e3a5f] hover:border-[#0891b2] bg-[#070d1a]"
              }`}
            >
              <div className="flex items-center justify-between mb-1">
                <div className="flex items-center gap-2">
                  <span className="text-[#00d4ff] text-[11px] font-bold">{coa.id}</span>
                  <span className="text-[#94a3b8] text-[11px]">{coa.name}</span>
                </div>
                <div className="flex items-center gap-2">
                  <span
                    className="text-[9px] font-mono px-1.5 py-0.5 rounded"
                    style={{
                      color: COA_STATUS_COLOR[coa.status],
                      borderWidth: 1,
                      borderStyle: "solid",
                      borderColor: COA_STATUS_COLOR[coa.status],
                    }}
                  >
                    {coa.status.replace("_", " ")}
                  </span>
                  <span
                    className="text-[9px] font-mono px-1.5 py-0.5 rounded"
                    style={{
                      color: RISK_COLOR[coa.risk],
                      borderWidth: 1,
                      borderStyle: "solid",
                      borderColor: RISK_COLOR[coa.risk],
                    }}
                  >
                    {coa.risk} RISK
                  </span>
                </div>
              </div>
              <div className="flex flex-wrap gap-1 mt-1">
                {coa.capabilities.map((cap) => (
                  <span key={cap} className="text-[8px] font-mono text-[#475569] bg-[#1e3a5f] px-1.5 py-0.5 rounded">
                    {cap}
                  </span>
                ))}
              </div>
            </button>
          ))}
        </div>

        {/* COA Summary */}
        {activeCOA && (
          <div className="mt-3 p-3 border border-[#1e3a5f] rounded bg-[#0a1628] space-y-2">
            <div className="grid grid-cols-2 gap-x-6 gap-y-2 text-[10px]">
              <div>
                <span className="text-[#475569]">Risk Level: </span>
                <span className="font-bold px-1.5 py-0.5 rounded" style={{ color: RISK_COLOR[activeCOA.risk] }}>
                  {activeCOA.risk}
                </span>
              </div>
              <div>
                <span className="text-[#475569]">Time to Effect: </span>
                <span className="text-[#94a3b8]">{activeCOA.timeToEffect}</span>
              </div>
              <div className="col-span-2">
                <span className="text-[#475569]">Success Probability: </span>
                <span className="text-[#00d4ff] font-mono">{activeCOA.successProbability}%</span>
                <div className="confidence-bar h-1.5 mt-1">
                  <div
                    className="confidence-fill"
                    style={{
                      width: `${activeCOA.successProbability}%`,
                      background:
                        activeCOA.successProbability >= 70
                          ? "#10b981"
                          : activeCOA.successProbability >= 40
                            ? "#f59e0b"
                            : "#ef4444",
                    }}
                  />
                </div>
              </div>
              <div className="col-span-2">
                <span className="text-[#475569]">Lines of Effort:</span>
                <ul className="mt-1 space-y-0.5">
                  {activeCOA.linesOfEffort.map((loe, i) => (
                    <li key={i} className="text-[#94a3b8] text-[10px] ml-3">- {loe}</li>
                  ))}
                </ul>
              </div>
              <div className="col-span-2 flex items-center gap-2">
                <span className="text-[#475569]">Posture: </span>
                <span
                  className="font-bold text-[10px] px-2 py-0.5 rounded"
                  style={{
                    color: POSTURE_COLOR[activeCOA.posture],
                    borderWidth: 1,
                    borderStyle: "solid",
                    borderColor: POSTURE_COLOR[activeCOA.posture],
                  }}
                >
                  {activeCOA.posture}
                </span>
              </div>
            </div>
            <div className="text-[10px] text-[#0891b2] font-mono mt-2">
              Annex will be generated using {activeCOA.id}: {activeCOA.name}
            </div>
            <button
              onClick={() => setPreviewImpact((p) => !p)}
              className={`mt-1 px-3 py-1 text-[10px] font-bold tracking-wider border rounded transition-colors ${
                previewImpact
                  ? "border-[#00d4ff] text-[#00d4ff] bg-[#00d4ff10]"
                  : "border-[#1e3a5f] text-[#475569] hover:border-[#0891b2]"
              }`}
            >
              {previewImpact ? "HIDE ANNEX IMPACT" : "PREVIEW ANNEX IMPACT"}
            </button>
          </div>
        )}
      </div>

      {/* ── Annex Preview Impact ──────────────────────────────────────── */}
      {previewImpact && activeCOA && (
        <div className="p-4 border border-[#0891b2] bg-[#0891b208] rounded space-y-3">
          <div className="text-[#00d4ff] text-[10px] font-bold tracking-widest">ANNEX IMPACT PREVIEW</div>

          {/* Tasks */}
          <div>
            <div className="text-[#94a3b8] text-[9px] font-bold tracking-wider mb-1">TASKS</div>
            <div className="space-y-1">
              {activeCOA.tasks.map((t) => (
                <div key={t.id} className="flex items-start gap-2 text-[10px]">
                  <span className="text-[8px] font-mono text-[#475569] bg-[#1e3a5f] px-1.5 py-0.5 rounded flex-shrink-0">
                    {t.capability}
                  </span>
                  <span className="text-[#94a3b8]">{t.description}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Authorities */}
          <div>
            <div className="text-[#94a3b8] text-[9px] font-bold tracking-wider mb-1">AUTHORITIES</div>
            <div className="space-y-1">
              {activeCOA.authorityRequirements.map((a, i) => (
                <div key={i} className="flex items-center gap-2 text-[10px]">
                  <span
                    className="text-[8px] font-mono px-1.5 py-0.5 rounded"
                    style={{
                      color: AUTH_STATUS_COLOR[a.status],
                      borderWidth: 1,
                      borderStyle: "solid",
                      borderColor: AUTH_STATUS_COLOR[a.status],
                    }}
                  >
                    {a.status.replace("_", " ")}
                  </span>
                  <span className="text-[#94a3b8]">{a.authority}</span>
                  <span className="text-[#475569]">({a.capability})</span>
                </div>
              ))}
            </div>
          </div>

          {/* Information Effects */}
          <div>
            <div className="text-[#94a3b8] text-[9px] font-bold tracking-wider mb-1">INFORMATION EFFECTS</div>
            <div className="space-y-1">
              {activeCOA.informationEffects.map((e) => (
                <div key={e.id} className="flex items-center gap-2 text-[10px]">
                  <span className="text-[#00d4ff] font-mono text-[9px]">{e.effectType}</span>
                  <span className="text-[#94a3b8]">{e.target}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Posture note */}
          <div className="text-[10px] font-mono pt-1 border-t border-[#1e3a5f]">
            <span className="text-[#475569]">Document language will use </span>
            <span style={{ color: POSTURE_COLOR[activeCOA.posture] }}>{activeCOA.posture}</span>
            <span className="text-[#475569]"> tone</span>
          </div>
        </div>
      )}

      {/* ── Doc Type Tabs ─────────────────────────────────────────────── */}
      <div className="flex gap-2">
        {([
          { id: "annex-i" as DocType, label: "ANNEX I (INFORMATION)", subtitle: "Full IO Annex to OPORD" },
          { id: "itco" as DocType, label: "ITCO", subtitle: "Info Tasking & Coordination Order" },
        ]).map((doc) => (
          <button
            key={doc.id}
            onClick={() => {
              setActiveDoc(doc.id);
              clearAnnexState();
            }}
            className={`flex-1 p-3 border rounded text-left transition-colors ${
              activeDoc === doc.id
                ? "border-[#00d4ff] bg-[#00d4ff10]"
                : "border-[#1e3a5f] hover:border-[#0891b2]"
            }`}
          >
            <div className={`text-xs font-bold ${activeDoc === doc.id ? "text-[#00d4ff]" : "text-[#94a3b8]"}`}>
              {doc.label}
            </div>
            <div className="text-[#475569] text-[10px] mt-0.5">{doc.subtitle}</div>
          </button>
        ))}
      </div>

      {/* ── Generation Parameters ─────────────────────────────────────── */}
      <div className="p-3 border border-[#1e3a5f] bg-[#070d1a] rounded">
        <div className="text-[#475569] text-[10px] tracking-wider mb-2">GENERATION PARAMETERS</div>
        <div className="grid grid-cols-3 gap-3 text-[10px]">
          <div>
            <span className="text-[#475569]">Selected COA: </span>
            {activeCOA ? (
              <span className="text-[#00d4ff] font-bold">{activeCOA.id} ({activeCOA.name})</span>
            ) : (
              <span className="text-[#ef4444] font-bold">NONE SELECTED</span>
            )}
          </div>
          <div>
            <span className="text-[#475569]">COA Status: </span>
            {activeCOA ? (
              <span className="font-bold" style={{ color: COA_STATUS_COLOR[activeCOA.status] }}>
                {activeCOA.status.replace("_", " ")}
              </span>
            ) : (
              <span className="text-[#475569]">--</span>
            )}
          </div>
          <div>
            <span className="text-[#475569]">IE Priority: </span>
            <span className="text-[#10b981] font-bold">{runningEstimate.priority}</span>
          </div>
          <div>
            <span className="text-[#475569]">Classification: </span>
            <span className="text-[#f59e0b] font-bold">{runningEstimate.classification}</span>
          </div>
          <div>
            <span className="text-[#475569]">DTG: </span>
            <span className="text-[#94a3b8] font-mono">{runningEstimate.dtg}</span>
          </div>
          <div>
            <span className="text-[#475569]">Operation: </span>
            <span className="text-[#94a3b8]">{runningEstimate.operationName}</span>
          </div>
          <div>
            <span className="text-[#475569]">Planning Tool: </span>
            <span className="text-[#94a3b8]">IE-SYNC v2.1</span>
          </div>
        </div>
      </div>

      {/* ── Warnings Panel ────────────────────────────────────────────── */}
      {lastGeneratedAnnex && lastGeneratedAnnex.warnings.length > 0 && (
        <div className="p-3 border border-[#f59e0b50] bg-[#f59e0b08] rounded space-y-1.5">
          <div className="text-[#f59e0b] text-[10px] font-bold tracking-wider">GENERATION WARNINGS</div>
          {lastGeneratedAnnex.warnings.map((w, i) => (
            <div key={i} className="flex items-start gap-2 text-[10px]">
              <span className="text-[#f59e0b] flex-shrink-0">!</span>
              <span className="text-[#94a3b8]">{w}</span>
            </div>
          ))}
        </div>
      )}

      {/* ── Generation Error ──────────────────────────────────────────── */}
      {genError && (
        <div className="p-3 border border-[#ef4444] bg-[#ef444408] rounded flex items-start gap-2">
          <span className="text-[#ef4444] flex-shrink-0">X</span>
          <div className="text-[10px] text-[#ef4444]">
            <span className="font-bold">GENERATION FAILED: </span>{genError}
          </div>
        </div>
      )}

      {/* ── Generation Progress ───────────────────────────────────────── */}
      {annexGenerating && (
        <div className="p-4 border border-[#0891b2] bg-[#0891b208] rounded">
          <div className="flex items-center justify-between mb-2 text-xs">
            <span className="text-[#00d4ff] font-bold">IO PLANNING ASSISTANT — GENERATING DOCUMENT</span>
            <span className="text-[#00d4ff] font-mono">{annexGenProgress}%</span>
          </div>
          <div className="confidence-bar h-2 mb-3">
            <div
              className="confidence-fill"
              style={{ width: `${annexGenProgress}%`, background: "#00d4ff" }}
            />
          </div>
          <div className="text-[#475569] text-[10px] font-mono space-y-0.5">
            {annexGenProgress >= 10 && <div>* Ingesting Running Estimate and COA parameters...</div>}
            {annexGenProgress >= 30 && <div>* Fusing COA tasks and authority requirements...</div>}
            {annexGenProgress >= 50 && <div>* Generating operational language (STANAG 6001)...</div>}
            {annexGenProgress >= 70 && <div>* Formatting per MCDP 5 / MCWP 3-32.1 standards...</div>}
            {annexGenProgress >= 85 && <div>* Applying classification markings and COA linkage...</div>}
            {annexGenProgress >= 95 && <div>* Running consistency and doctrinal compliance check...</div>}
            {annexGenProgress >= 100 && <div className="text-[#10b981]">Document generation complete.</div>}
          </div>
        </div>
      )}

      {/* ── Document Output ───────────────────────────────────────────── */}
      <div className="tactical-card">
        <div className="px-4 py-3 border-b border-[#1e3a5f] flex items-center justify-between">
          <div className="text-[#00d4ff] text-xs font-bold tracking-widest">
            {activeDoc === "annex-i" ? "ANNEX I (INFORMATION) — DRAFT OUTPUT" : "ITCO — DRAFT OUTPUT"}
          </div>
          <div className="flex items-center gap-2 flex-wrap">
            {lastGeneratedAnnex && (
              <span className="text-[10px] text-[#10b981] font-mono">DRAFT COMPLETE // HUMAN REVIEW REQUIRED</span>
            )}
            {lastGeneratedAnnex && (
              <>
                <button
                  onClick={handleExportTXT}
                  className="px-2 py-1 text-[10px] border border-[#0891b2] text-[#00d4ff] rounded hover:bg-[#0891b215] font-mono"
                  title="Export as plain text with COA metadata header"
                >
                  TXT
                </button>
                <button
                  onClick={handleExportJSON}
                  className="px-2 py-1 text-[10px] border border-[#1e3a5f] text-[#475569] rounded hover:bg-[#1e3a5f30] font-mono"
                  title="Export as JSON with full COA linkage and metadata"
                >
                  JSON
                </button>
                <button
                  onClick={handleCopy}
                  className={`px-2 py-1 text-[10px] border rounded font-mono transition-colors ${
                    copied
                      ? "border-[#10b981] text-[#10b981] bg-[#10b98115]"
                      : "border-[#1e3a5f] text-[#475569] hover:border-[#334155]"
                  }`}
                  title="Copy document text to clipboard"
                >
                  {copied ? "COPIED" : "COPY"}
                </button>
              </>
            )}
          </div>
        </div>
        <div className="p-4">
          {lastGeneratedAnnex ? (
            <pre className="text-[11px] text-[#e2e8f0] font-mono leading-relaxed whitespace-pre-wrap overflow-auto max-h-[500px] bg-[#070d1a] p-4 rounded border border-[#1e3a5f]">
              {lastGeneratedAnnex.content}
            </pre>
          ) : (
            <div className="flex flex-col items-center justify-center h-48 text-center">
              <div className="text-[#1e3a5f] text-4xl mb-4">&#9639;</div>
              <div className="text-[#475569] text-sm mb-2">Document not yet generated</div>
              <div className="text-[#334155] text-xs max-w-sm">
                {selectedCOA
                  ? `Click "GENERATE DOCUMENT" to produce a draft ${activeDoc === "annex-i" ? "Annex I" : "ITCO"} based on ${activeCOA?.id}: ${activeCOA?.name}. All output requires human analyst review before commander briefing.`
                  : `Select a Course of Action above, then click "GENERATE DOCUMENT" to produce a draft ${activeDoc === "annex-i" ? "Annex I" : "ITCO"}. All output requires human analyst review.`}
              </div>
            </div>
          )}
        </div>
      </div>

      {/* ── Review Lanes ──────────────────────────────────────────────── */}
      {lastGeneratedAnnex && activeCOA && (
        <ReviewLanes docType={activeDoc} coa={activeCOA} />
      )}

      {/* ── Commander Advisory ────────────────────────────────────────── */}
      <div className="p-3 border border-[#f59e0b50] bg-[#f59e0b08] rounded flex items-start gap-2">
        <span className="text-[#f59e0b] flex-shrink-0">!</span>
        <div className="text-[10px] text-[#94a3b8]">
          <span className="text-[#f59e0b] font-bold">COMMANDER ADVISORY: </span>
          AI-assisted planning documents require human analyst review and commander approval prior to release or dissemination. Legal review required for all DCO and EW actions. PA releases require PAO approval. This tool is an aid to planning — judgment and accountability rest with the responsible officer.
        </div>
      </div>

      {/* ── Glossary ──────────────────────────────────────────────────── */}
      <GlossaryPanel module="annex" />
    </div>
  );
}

// ── Review Lanes — COA-aware sign-off checklist ───────────────────────────
function ReviewLanes({ docType, coa }: { docType: DocType; coa: COAOption }) {
  const capabilities = coa.capabilities;

  const buildLanes = () => {
    const lanes: { role: string; requirement: string; required: boolean }[] = [];

    if (docType === "annex-i") {
      lanes.push(
        { role: "IO OFFICER", requirement: "Validate all IO tasks against current OPORD and commander's intent", required: true },
        { role: "LEGAL (JAG)", requirement: "Review CYBER (Title 10/50) and EW deconfliction authorities", required: true },
      );
      if (capabilities.includes("PA")) {
        lanes.push({ role: "PAO", requirement: "Approve all PA tasks and public messaging prior to release", required: true });
      }
      if (capabilities.includes("MISO")) {
        lanes.push({ role: "PSYOP AUTH", requirement: "Approve MISO products (USSOCOM PSYOP approval authority)", required: true });
      }
      if (capabilities.includes("CYBER")) {
        lanes.push({ role: "CYBERCOM AUTHORITY", requirement: "Validate DCO/OCO authorities and Title 10/50 compliance", required: true });
      }
      if (capabilities.includes("EW")) {
        lanes.push({ role: "EW DECONFLICTION", requirement: "Deconflict electromagnetic spectrum usage via JFC-IMC", required: true });
      }
      lanes.push(
        { role: "COMMANDER", requirement: "Final approval before dissemination or execution", required: true },
      );
    } else {
      // ITCO lanes
      lanes.push(
        { role: "IO OFFICER", requirement: "Validate all task owners, NLT timings, and capability authorities", required: true },
        { role: "LEGAL (JAG)", requirement: "Title 10/50 review for CYBER tasks; EW authority confirmation", required: true },
      );
      if (capabilities.includes("PA")) {
        lanes.push({ role: "PAO", requirement: "Review PA task language and release authority", required: true });
      }
      if (capabilities.includes("MISO")) {
        lanes.push({ role: "PSYOP AUTH", requirement: "Approve MISO products (USSOCOM PSYOP approval authority)", required: true });
      }
      if (capabilities.includes("CYBER")) {
        lanes.push({ role: "CYBERCOM AUTHORITY", requirement: "Validate DCO/OCO authorities and Title 10/50 compliance", required: true });
      }
      if (capabilities.includes("EW")) {
        lanes.push({ role: "EW DECONFLICTION", requirement: "Deconflict electromagnetic spectrum usage via JFC-IMC", required: true });
      }
      lanes.push(
        { role: "OPS SGT MAJ", requirement: "Confirm resource availability and execution feasibility", required: false },
      );
    }
    return lanes;
  };

  const lanes = buildLanes();

  const [checkedAt, setCheckedAt] = useState<Record<string, string | null>>({});
  const isChecked = (role: string) => checkedAt[role] != null;
  const allRequired = lanes.filter((l) => l.required).every((l) => isChecked(l.role));

  const toggleLane = (role: string) => {
    setCheckedAt((c) => ({
      ...c,
      [role]: c[role] != null ? null : new Date().toISOString().substring(11, 16),
    }));
  };

  return (
    <div className="tactical-card p-4">
      <div className="flex items-center justify-between mb-3">
        <div className="text-[#00d4ff] text-xs font-bold tracking-widest">REVIEW LANES — SIGN-OFF CHECKLIST</div>
        {allRequired ? (
          <span className="text-[9px] text-[#10b981] border border-[#10b981] px-2 py-0.5 rounded font-mono">ALL REQUIRED REVIEWS COMPLETE</span>
        ) : (
          <span className="text-[9px] text-[#ef4444] border border-[#ef4444] px-2 py-0.5 rounded font-mono">PENDING REQUIRED REVIEWS</span>
        )}
      </div>
      <div className="space-y-2">
        {lanes.map((lane) => (
          <div
            key={lane.role}
            className={`flex items-start gap-3 p-2.5 border rounded transition-colors ${
              isChecked(lane.role) ? "border-[#10b981] bg-[#10b98108]" : "border-[#1e3a5f] bg-[#070d1a]"
            }`}
          >
            <button
              onClick={() => toggleLane(lane.role)}
              className={`flex-shrink-0 w-4 h-4 border rounded mt-0.5 flex items-center justify-center text-[9px] font-bold ${
                isChecked(lane.role) ? "border-[#10b981] bg-[#10b98130] text-[#10b981]" : "border-[#334155] text-[#334155]"
              }`}
            >
              {isChecked(lane.role) ? "v" : ""}
            </button>
            <div className="flex-1">
              <div className="flex items-center gap-2">
                <span className="text-[#00d4ff] text-[10px] font-bold">{lane.role}</span>
                {lane.required && (
                  <span className="text-[9px] text-[#ef4444] font-mono">REQUIRED</span>
                )}
              </div>
              <div className="text-[#94a3b8] text-[9px] mt-0.5">{lane.requirement}</div>
            </div>
            <div className="text-[9px] text-[#475569] font-mono flex-shrink-0">
              {isChecked(lane.role) ? `v ${checkedAt[lane.role]}Z` : "PENDING"}
            </div>
          </div>
        ))}
      </div>
      <div className="mt-2 text-[9px] text-[#334155] font-mono">
        Mark each lane complete after receiving written or verbal confirmation from the responsible officer.
        This checklist is local-session only and does not persist across browser sessions.
      </div>
    </div>
  );
}
